---
- name: API servers
  hosts: api_servers
  sudo: yes

  vars:
    nginx_server_name: "{{ nginx_api_server_name }}"
    nginx_serve_user_docs: False

  roles:
    - { role: secrets, tags: ["pre", "secrets"] }
    - { role: environment, tags: ["pre", "environment"] }
    - { role: common, tags: ["common"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: virtualenv, tags: ["virtualenv"] }
    - { role: app_code, tags: ["app", "app.code"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: supervisor, tags: ["supervisor"] }
    - { role: uwsgi, tags: ["uwsgi"] }


