---
- name: Database servers
  hosts: db_servers
  sudo: yes

  roles:
    - { role: secrets, tags: ["pre", "secrets"] }
    - { role: environment, tags: ["pre", "environment"] }
    - { role: common, tags: ["common"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: postgres, tags: ["postgres"] }

