---
- name: Management servers
  hosts: management_servers
  sudo: yes

  roles:
    - { role: secrets, tags: ["pre", "secrets"] }
    - { role: environment, tags: ["pre", "environment"] }
    - { role: common, tags: ["common"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: virtualenv, tags: ["virtualenv"] }
    - { role: app_code, tags: ["app", "app.code"] }
    - { role: app_db, tags: ["app", "app.db"] }

  handlers:
    - name: restart uwsgi
      shell: "/bin/true"

