---
- name: One box servers
  hosts: onebox_servers
  sudo: yes

  vars:
    nginx_server_name: "{{ nginx_app_server_name }}"

  roles:
    - { role: secrets, tags: ["pre", "secrets"] }
    - { role: environment, tags: ["pre", "environment"] }
    - { role: common, tags: ["common"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: postgres, tags: ["postgres"] }
    - { role: virtualenv, tags: ["virtualenv"] }
    - { role: app_code, tags: ["app", "app.code"] }
    - { role: app_db, tags: ["app", "app.db"] }
    - { role: app_static, tags: ["app", "app.static"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: supervisor, tags: ["nginx"] }
    - { role: uwsgi, tags: ["uwsgi"] }
    - { role: vagrant_web, tags: ["vargant_web"], when: dev }
