# -*- mode: yaml -*-
# If you change these values make sure to update the
# corresponding entry in the secret_env var below.
db_user: "ubuntu"
db_password: "M33tD3ck.14!"
django_settings_module: "crunchy.settings.production"
django_secret_key: "bs-ll4(fe5aj+q135x1ol+fqfp7t21_6r1!=(q8aqycosvzwwz"

django_env:
  DJANGO_SETTINGS_MODULE: "crunchy.settings.production"
  ML_DB_USER: "ubuntu"
  ML_DB_PASSWORD: "M33tD3ck.14!"
  ML_DJANGO_SECRET_KEY: "bs-ll4(fe5aj+q135x1ol+fqfp7t21_6r1!=(q8aqycosvzwwz"